[tool.poetry]
name = "trader"
version = "0.1.0"
description = ""
authors = ["Mischa Spiegelmock <me@mish.dev>"]

[tool.poetry.dependencies]
#pyjuque = "^0.1.1"
pyjuque = { git = "https://github.com/revmischa/pyjuque.git", rev = "f4aee7945ebf374736c3d091dd8cbe29165d4c41" }
python = "^3.8"
pandas-ta = "^0.3.14-beta.0"
TA-Lib = "0.4.19"
hyperopt = "^0.2.5"
matplotlib = "^3.4.3"
python-dotenv = "0.15.0"
ipywidgets = "^7.6.4"

[tool.poetry.dev-dependencies]
black = "^21.7b0"
epc = "^0.0.5"
importmagic = "^0.1.7"
ipython = "^7.26.0"
jupyterlab = "^3.1.7"
python-dotenv = "0.15.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
